version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 13o1714QO^WXep@A
      POSTGRES_USER: trace
      POSTGRES_DB: trace
    volumes:
      - ./pgdata:/var/lib/postgresql/data
